version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: 'nginx'
    ports:
      - '8100:80'
      - '8200:81'
    volumes:
      # Application testing
      - ./frontend/web:/app/frontend/web:delegated
      - ./backend/web:/app/backend/web:delegated
    links:
      - php
  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./:/app:delegated
      # Composer cache
      - ~/.composer/cache:/root/.composer/cache:delegated
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: yii2advanced
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

#  db:
#    image: postgres:13-alpine
#    environment:
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: yii2advanced
#    volumes:
#      - ./db/data:/var/lib/postgresql/data
#      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
