<?php
/**
 * Project: yii2-blog for internal using
 * Author: akiraz2
 * Copyright (c) 2018.
 */

namespace backend\components;

use yii\filters\AccessControl;

class AdminAccessControl extends AccessControl
{

    public function init()
    {
        $this->rules[] =[
            'allow' => true,
            'roles' => ['@'],
            'matchCallback' => function () {
                return \Yii::$app->user->identity->getIsAdmin();
            }
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}